### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wanghang2017** [connesc/co-wrap-all#2]
npm error 404  when  i use  command  "npm  i  co-wrap-all"

**Comment by connesc** [comment]
No problem on my side, maybe your are using a custom registry?

**Comment by wanghang2017** [comment]
> No problem on my side, maybe your are using a custom registry?

Thanks!   I resolved it by changing registry  default to registry https://registry.npm.taobao.org  just now !

**Comment by connesc** [comment]
Great!
